name: Pre-release

# on:
#     push:
#         branches: 
#             - release/**

on: workflow_dispatch

jobs:
    CustomEnvironmentVariables:
        runs-on: windows-latest

        strategy:
            matrix:
                node-version: [14.x]

        outputs:
            currentBranch: ${{ steps.setCurrentBranch.outputs.test }}
            currentVersion: ${{ steps.setCurrentVersion.outputs.test }}
        
        steps:
            - id: setCurrentVersion
              shell: node
              run: echo "::set-output name=test::${{ github.ref.replace('release/', '') }}"
            - id: setCurrentBranch
              run: echo "::set-output name=test::${{github.ref}}"

    OutputEnvironmentVariables:
        runs-on: windows-latest

        strategy:
            matrix:
                node-version: [14.x]

        needs: CustomEnvironmentVariables

        steps:
            - run: echo ${{needs.CustomEnvironmentVariables.outputs.currentBranch}}
            - run: echo ${{needs.CustomEnvironmentVariables.outputs.currentVersion}}

# steps:
#     - name: Checkout
#       uses: actions/checkout@v2
#       with:
#             ref: ${{ github.ref }}
#     - run: echo ${{ github.ref }}