name: Pre-release

# on:
#     push:
#         branches: 
#             - release/**

on: workflow_dispatch

jobs:
    CustomEnvironmentVariables:
        runs-on: windows-latest

        strategy:
            matrix:
                node-version: [14.x]

        outputs:
            currentBranch: ${{ steps.setCurrentVersion.outputs.value }}
            currentVersion: ${{ steps.setCurrentBranch.outputs.value }}
        
        steps:
            - id: setCurrentVersion
            #   run: echo "::set-output name=test::${{github.ref}}"
              run: |
                ref = "${{github.ref}}";
                varsion = "${ref/$'refs/heads/release/'/''}"
                echo "::set-output name=value::$version"
              shell: bash
            - id: setCurrentBranch
              run: echo "::set-output name=value::${{github.ref}}"

    OutputEnvironmentVariables:
        runs-on: windows-latest

        strategy:
            matrix:
                node-version: [14.x]

        needs: CustomEnvironmentVariables

        steps:
            - run: echo ${{needs.CustomEnvironmentVariables.outputs.currentBranch}}
            - run: echo ${{needs.CustomEnvironmentVariables.outputs.currentVersion}}

# steps:
#     - name: Checkout
#       uses: actions/checkout@v2
#       with:
#             ref: ${{ github.ref }}
#     - run: echo ${{ github.ref }}