name: Pre-release

on:
    push:
        branches: 
            - release/**

# on: workflow_dispatch

jobs:
    CustomEnvironmentVariables:
        runs-on: windows-latest

        strategy:
            matrix:
                node-version: [14.x]

        outputs:
            projectName: ${{ steps.setProjectName.outputs.value }}
            currentBranch: ${{ steps.setCurrentBranch.outputs.value }}
            currentVersion: ${{ steps.setCurrentVersion.outputs.value }}
            
        steps:
            - name: Checkout.
              uses: actions/checkout@v2
              with:
                fetch-depth: 0

            - id: setCurrentVersion
              run: |
                ref="${{github.ref}}"
                version="${ref//$'refs/heads/release/'/''}"
                echo "::set-output name=value::$version"
              shell: bash
            
            - id: setCurrentBranch
              run: echo "::set-output name=value::${{github.ref}}"
            
            - id: package
              uses: codex-team/action-nodejs-package-info@v1

            - id: setProjectName
              run: echo "::set-output name=value::${{steps.package.outputs.name}}"

    # DeleteRelease:
    #     runs-on: windows-latest

    #     strategy:
    #         matrix:
    #             node-version: [14.x]
        
    #     needs: CustomEnvironmentVariables

    #     steps:
    #         - run: echo "v${{needs.CustomEnvironmentVariables.outputs.currentVersion}}-beta"
    #         - uses: dev-drprasad/delete-tag-and-release@v0.2.0
    #           with:
    #               delete_release: true
    #               tag_name: "v${{needs.CustomEnvironmentVariables.outputs.currentVersion}}-beta"
    #           env:
    #               GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}


    # OutputEnvironmentVariables:
    #     runs-on: windows-latest

    #     strategy:
    #         matrix:
    #             node-version: [14.x]

    #     needs: CustomEnvironmentVariables

    #     steps:
    #         - run: echo ${{needs.CustomEnvironmentVariables.outputs.projectName}}
    #         - run: echo ${{needs.CustomEnvironmentVariables.outputs.currentBranch}}
    #         - run: echo ${{needs.CustomEnvironmentVariables.outputs.currentVersion}}

    Build:
        runs-on: windows-latest

        strategy:
            matrix:
                node-version: [14.x]

        needs: CustomEnvironmentVariables

        steps:
            - name: Checkout.
              uses: actions/checkout@v2
              with:
                fetch-depth: 0
            
            - name: Install dependencies.
              run: npm install
            
            - name: Build project.
              run: npm run build

            - name: Generate changelog.
              run: npm run changelog

            - name: Remove release
              uses: dev-drprasad/delete-tag-and-release@v0.2.0
              with:
                  tag_name: "v${{needs.CustomEnvironmentVariables.outputs.currentVersion}}-Preview"
                  delete_release: true
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

            - name: Publish release.
              uses: softprops/action-gh-release@v1
              with:
                  prerelease: ${{true}}
                  tag_name: "v${{needs.CustomEnvironmentVariables.outputs.currentVersion}}-Preview"
                  target_commitish: ${{GITHUB_SHA}}
                  name: "${{needs.CustomEnvironmentVariables.outputs.projectName}} Preview v${{needs.CustomEnvironmentVariables.outputs.currentVersion}}"
                  body_path: "${{github.workspace}}\\CHANGELOG.md"
                  token: ${{github.token}}
                  files: |
                      dist
                      index.html
