name: Pre-release

# on:
#     push:
#         branches: 
#             - release/**

on: workflow_dispatch

jobs:
    CustomEnvironmentVariables:
        runs-on: windows-latest

        strategy:
            matrix:
                node-version: [14.x]

        outputs:
            currentBranch: ${{ steps.setCurrentVersion.outputs.value }}
            currentVersion: ${{ steps.setCurrentBranch.outputs.value }}
        
        steps:
            - id: setCurrentVersion
            #   run: echo "::set-output name=test::${{github.ref}}"
              run: |
                ref="${{github.ref}}"
                version="${ref//$'refs/heads/release/'/''}"
                echo "::set-output name=value::$version"
              shell: bash
            - id: setCurrentBranch
              run: echo "::set-output name=value::${{github.ref}}"

    Build:
        runs-on: windows-latest

        strategy:
            matrix:
                node-version: [14.x]

        needs: CustomEnvironmentVariables

        steps:
            - name: Checkout.
              uses: actions/checkout@v2
              with:
                ref: ${{ needs.CustomEnvironmentVariables.outputs.currentBranch }}
            
            - name: Install dependencies.
              run: npm install
            
            - name: Build project.
              run: npm run build

            - name: Generate changelog.
              run: npm run changelog

            - name: Publish release.
              uses: softprops/action-gh-release@v1
              with:
                draft: true,
                prerelease: true,
                name: ${{ needs.CustomEnvironmentVariables.outputs.currentVersion }}
                body_path: ${{ github.workspace }}-CHANGELOG.md
                token: ${{ secrets.CUSTOM_GITHUB_TOKEN }}
                files: |
                  dist
                  index.html
            


# OutputEnvironmentVariables:
#     runs-on: windows-latest

#     strategy:
#         matrix:
#             node-version: [14.x]

#     needs: CustomEnvironmentVariables

#     steps:
#         - run: echo ${{needs.CustomEnvironmentVariables.outputs.currentBranch}}
#         - run: echo ${{needs.CustomEnvironmentVariables.outputs.currentVersion}}

# steps:
#     - name: Checkout
#       uses: actions/checkout@v2
#       with:
#             ref: ${{ github.ref }}
#     - run: echo ${{ github.ref }}